- config/game_options.txt
- config/jobconfig.toml
- config/skyrat/skyrat_config.txt
- modular_ss220/modules/jobs/jobs.dm
- modular_ss220/modules/mutant_parts/body_size.dm
- modular_ss220/modules/mutant_parts/taur.dm
- tgstation.dme
> SS220 Config

- code/_compile_options.dm
> Use external CDN

- code/__HELPERS/text.dm
- code/datums/keybinding/communication.dm
- code/modules/client/client_procs.dm
- code/modules/client/preferences/middleware/keybindings.dm
- modular_skyrat/modules/customization/datums/keybinding/communication.dm
> Cyrillic key fixes

- config/game_options.txt
> Set correct speed modifiers

- config/game_options.txt
This reverts commit dce6b193f420c9eb01ac158158255569d538bfcf.
<details>
</details>
> Revert "Set correct speed modifiers (#8)"

- .github/workflows/ci_suite.yml
- skyrat/tools/ss220_check_grep.sh
Adds CI check
-
-
<details>
</details>
:cl:
add: CI for modular_ss220
/:cl:
> Add CI for modular_ss220

- tools/build/build.js
- tools/validate_dme.py
> FIX: correct dm validation

- code/__HELPERS/text.dm
Добавляет возможность ставить киррилицу в имена.
Не знаю и не думаю, что это возможность сделать модульно, не заменяя полностью их reject_bad_name
<details>
<summary>
</summary>
</details>
:cl:
add: Cyrillic support for names
/:cl:
> feat: Cyrillic names

- modular_ss220/modules/mutant_parts/species.dm
- tgstation.dme
Исправляет непроходимость тестов.
CI
<details>
</details>
:cl:
fix: Integration tests
/:cl:
> Fix: Integration tests

- .github/workflows/conflicts.yml
Better merge conflict detection
Better merge conflict detection
<details>
</details>
:cl:
add: Better merge conflict detection
/:cl:
> Add: Better merge conflict detection

- config/config.txt
- config/ss220/ss220_config.txt
> Add TTS config to separate ss220 dir

- modular_ss220/modules/tts/code/_tts_defines.dm
- modular_ss220/modules/tts/code/_tts_rust_g_ss220.dm
- modular_ss220/modules/tts/code/tts_subsystem.dm
- modular_ss220/modules/tts/code/~undefs/~tts_undefs.dm
- tgstation.dme
Параллельная работа двух версий rust_g. Форка для ТТС и оригинальной для всего остального. Исправляет рантайм `rustg_unix_timestamp`.
Отсутствие рантайма `rustg_unix_timestamp`
> Make usage of both upstream rust_g and rust_g_ss220

- modular_ss220/modules/tts/code/tts_mob_Hear.dm
- tgstation.dme
TTS для мертвых и гостов
Мертвые и госты будут слышать ТТС
https://discord.com/channels/1097181193939730453/1097521716013568011/1104092133239033866
:cl:
fix: Fixed TTS for dead & observers
/:cl:
> Fix observers not hearing TTS

- code/controllers/configuration/entries/game_options.dm
Добавляет стандартную скорость базик-мобам
<details>
</details>
:cl:
add: support for basic mobs' speed
/:cl:
> feat: support for basic mobs' speed

- modular_ss220/modules/balance_changes/mobs/living_defines.dm
- modular_ss220/modules/balance_changes/weapons/baton/baton.dm
- tgstation.dme
- Возвращает здоровье до 100
- Возвращает урон станбатонов до стандартного (2 удара для крита)
:cl:
balance: return max human health back to 100 from 135
balance: return baton stamina damage back to 55 from 30
/:cl:
> Balance changes

- config/ss220/ss220_config.txt
- modular_ss220/prime/balance_changes/crawl_speed/crawl_speed.dm
- tgstation.dme
Added additional crawling slowdown (disabled by default)
:cl:
balance: Added additional crawling slowdown (disabled by default)
/:cl:
> feat: Additional crawling slowdown.

- tgui/packages/tgui/interfaces/PreferencesMenu/preferences/features/game_preferences/ss220/tts.tsx
Изменение настроек громкости ТТС на слайдеры.
Слайдеры для регулировки громкости привычны и логичны.
https://discord.com/channels/1097181193939730453/1097521716013568011/1104533200539234305
:cl:
qol: Made TTS volume options with sliders
/:cl:
> Rework TTS options with sliders

- code/modules/mob/living/damage_procs.dm
https://github.com/Skyrat-SS13/Skyrat-tg/pull/20992
> fix: stamina damage slows

- config/ss220/ss220_config.txt
> fix: wrong value

- modular_ss220/modules/tts/code/tts_mob_Hear.dm
Исправляет ошибку сборки билда.
Билд собирается.
> Fix build error

- modular_ss220/modules/tts/code/tts_mob_Hear.dm
Исправляет рантаймы в файле `mob_Hear`
Меньше рантаймов -- лучше.
> Fix mob_Hear runtimes

- tgui/packages/tgui/interfaces/PreferencesMenu/LimbsPage.tsx
Fixed augment page in character preferences
:cl:
fix: fixed augment page in character preferences
/:cl:
> Fix augment page

- modular_ss220/modules/tts/code/base_seeds/objs/objs.dm
tweak: remove TTS from modular computers
> tweak: remove TTS from modular computers

- html/changelogs/AutoChangeLog-pr-20983.yml
- html/changelogs/AutoChangeLog-pr-21048.yml
- html/changelogs/AutoChangeLog-pr-21049.yml
- html/changelogs/AutoChangeLog-pr-21050.yml
- html/changelogs/AutoChangeLog-pr-21051.yml
- html/changelogs/AutoChangeLog-pr-21061.yml
- html/changelogs/archive/2023-05.yml
- tgui/packages/tgui/interfaces/PreferencesMenu/LimbsPage.tsx
An automated PR to sync changes from the upstream
> [Sync] Pull Upstream

- modular_ss220/modules/tts/code/seeds/silero.dm
> Added new TTS voices

- code/game/gamemodes/dynamic/dynamic.dm
tweak: force 0 threat on lowpop
> tweak: force 0 threat on lowpop

- modular_ss220/master_files_skyrat/modules/wall_fungus/code/wall_fungus_event.dm
- tgstation.dme
Добавляние необходимости в 20 живых игроках для старта ивента с всепожирающим грибком на стенах
> rebalance wall-fungus min players

- modular_ss220/master_files_skyrat/modules/altborgs/code/robot_model.dm
- tgstation.dme
- Убирает скины жопного борга;
- Убирает маленькие скины для СБ и пискипер боргов
> tweak: Removed some borg icons

- modular_ss220/master_files_skyrat/modules/skyrat-uplinks/code/categories/stealthy_weapons.dm
- tgstation.dme
Убирает телескопичку из аплинка обычных трейторов
> tweak: removes telescbaton from traitor uplink

- modular_ss220/master_files_skyrat/modules/microfusion/code/projectiles.dm
- tgstation.dme
Продолжение https://github.com/tgstation/tgstation/pull/75329 для скайратовских лазеров. Увеличивает урон лазеров на 25%.
> tweak: x1.25 more damage for MCRs

- code/__DEFINES/logging.dm
- code/__DEFINES/~ss220_defines/logging.dm
- tgstation.dme
Добавляет аттак логи в логис, а также новые следующие:
1. Без категории
MONEY:
JOB:
MECHA:
PAPER:
SHUTTLE:
SILICON:
TOOL:
VIRUS:
SUSPICIOUS_ACCESS:
2. ПДАшные
COMMENT
CHAT:
3. Антажные
UPLINK:
MALF UPGRADE:
CHANGELING:
HERETIC RESEARCH:
SPELLBOOK:
BORER EVOLUTION:
> tweak: More logs for Logis!

- modular_skyrat/modules/hurtsposals/code/pipe.dm
Уменьшает урон от мусорки с 5 до 1-3. По идее, должно уменьшить количество убийств.
> nerf: Disposals damage

- code/__DEFINES/colors.dm
- modular_ss220/master_files_skyrat/modules/aesthetics/lights/code/lighting.dm
- modular_ss220/master_files_skyrat/modules/power/lighting/light_mapping_helpers.dm
- tgstation.dme
Возвращает освещение оригинального ТГ (приближенно к Паре: ярче, теплее), меняет цвет космоса на всем привычный (светло-голубой, вместо сиреневого).
PR Скайрата, который менял освещение:
https://github.com/Skyrat-SS13/Skyrat-tg/pull/20269
Приятнее играть в тёплом освещении, чем в холодном мраке
:cl:
add: Warm Lighting
/:cl:
> Feat: Warm Lighting

- modular_ss220/master_files_skyrat/modules/aesthetics/lights/code/lighting.dm
Cleanup coding skill issues
Fix coding skill issues
<details>
</details>
:cl:
fix: coding skill issues
/:cl:
> Fix: Warm Lighting code cleanup

- code/modules/client/preferences_savefile.dm
- config/ss220/ss220_config.txt
- modular_skyrat/modules/bsa_overhaul/code/bsa_cannon.dm
- modular_skyrat/modules/mapping/code/automatic_respawner.dm
- modular_skyrat/modules/modular_implants/code/nifs.dm
- modular_skyrat/modules/modular_implants/code/nifsofts.dm
- modular_skyrat/modules/modular_implants/code/nifsofts/money_sense.dm
- modular_skyrat/modules/modular_implants/code/nifsofts/prop_summoner.dm
- modular_skyrat/modules/time_clock/code/off_duty_component.dm
- modular_ss220/modules/tts/code/seeds/silero.dm
- modular_ss220/modules/tts/code/tts_configuration.dm
- modular_ss220/modules/tts/code/tts_sound.dm
- modular_ss220/modules/tts/code/tts_subsystem.dm
Стягивание некоторых полезных коммитов
-
-
:cl:
add: Steal commits
/:cl:
> Feat: Steal commits [1] [23/05/2023]

- modular_ss220/modules/tts/code/tts_subsystem.dm
Убирает Артаса как значение по-умолчанию, тем самым, убирая ТТС, где его быть не должно
> tweak: Remove Arthas as default tts

- code/datums/votes/map_vote.dm
Разрешает голосовать за текущую карту
> feat: can vote for the current map again!

- code/modules/modular_computers/computers/item/role_tablet_presets.dm
- code/modules/modular_computers/file_system/programs/budgetordering.dm
Добавляет возможность вардену использовать бюджет СБ.
Варден отвечает за оружейку и снаряжение, а не ГСБ.
Варден сидит в бриге, пока ГСБ ведёт охоту с Уникой/Глоком.
<details>
</details>
:cl:
balance: Warden allowed to use Security Budget
/:cl:
> feat: Warden allowed to use Security Budget

- _maps/map_files/Cyberiad/Cyberiad.dmm
Исправления карты Кибериада:
-  Добавлены ящики в карго;
-  Добавлена консоль с инженерным пресетом на вход в зону движка;
- Исправлено прямое подключение движка к сети станции;
-  Исправлено направление конвейерных лент в карго.
<details>
</details>
> Cyberiad: engine and cargo minor fixes

- _maps/map_files/Cyberiad/Cyberiad.dmm
Перестроены техи сервиса в холл сервиса.
Небольшая перестановка кухни в пользу большего количества столов и кухонных пренадлежностей.
Добавил мелочёвку бармену (не покажу).
Продолжение адаптации Кибериады под Скайрат.
<details>
<summary>Screenshots</summary>
Вид из игры
Вид из редактора
</details>
:cl:
add: Cyberiad: Сделан сервисный холл.
qol: Cyberiad: Перестановка кухни.
/:cl:
> Cyberiad: Service Hall & Kitchen

- modular_skyrat/modules/verbs/code/looc.dm
Добавляет возможность пользования LOOC мертвым и без сознания
> tweak: LOOC everywhere

- modular_ss220/modules/tts/code/base_seeds/objs/objs.dm
> tweak: Remove TTS from lathes

- modular_ss220/modules/tts/code/base_seeds/objs/objs.dm
> tweak: Removes TTS from exofab

- code/__HELPERS/roundend.dm
- code/modules/antagonists/abductor/abductor.dm
- code/modules/antagonists/changeling/changeling.dm
- code/modules/antagonists/heretic/heretic_antag.dm
- code/modules/antagonists/malf_ai/malf_ai.dm
> tweak: Returns greentext

- modular_ss220/modules/additional_crawl_speed/code/crawl_speed.dm
Такое же соотношение бега к ползанию, как у ТГ
> tweak: Crawl speed rebalance for 2.1 run delay

- _maps/map_files/Cyberiad/Cyberiad.dmm
Фикс проблем которые нашли игроки на Кибериаде.
А я не тестил xdd
:cl:
tweak: Improvements for Cyberiad
/:cl:
> Fixes for the best map

- modular_skyrat/modules/modular_implants/code/nifs.dm
- modular_skyrat/modules/time_clock/code/off_duty_component.dm
- modular_ss220/modules/redsec/code/clothes_bluesec.dm
- modular_ss220/modules/redsec/code/clothes_redsec.dm
> fix: Now it compiles

- modular_ss220/barsigns/code/barsigns.dm
- modular_ss220/redsec/code/miscellaneous.dm
Убирает лишний код
Компилирует код
:cl:
code: Код теперь компилируется
code: Убран лишний код у модуля барных вывесок
/:cl:
> [FIX] Исправление после мерджа

- modular_ss220/customization/_customization.dme
Включает в дме модуль кастомизаци. Забыл.
:cl:
fix: Veteran jobs are not Veteran anymore
fix: Correct removal of sexy borgs
/:cl:
> [FIX] customization module

- interface/skin.dmf
Обновляет шрифт
Красивое
<details>
До
После
</details>
:cl:
fix: made something easier to use
/:cl:
> [FIX] Update Font

- modular_ss220/crawl_speed/code/crawl_speed_component.dm
- modular_ss220/crawl_speed/code/crawl_speed_mob.dm
Чуть лучше выглядит, не дает компонент на логине, а когда нужно
Trust me
:cl:
refactor: Force Crawl Speed component now given on crawl, not on login
/:cl:
> [REFACTOR] Force walk speed on Crawl

- _maps/map_files/Cyberiad/Cyberiad.dmm
> [MAP] Move Cyberiad mobs from water to fix CI

- tools/json_verifier.py
Перемещает проверку на ss220 исключение json в try из except. Посмотрим, починит ли линтер...
> SS220 json exception linter fix???

- tools/json_verifier.py
- tools/validate_dme.py
- fixes json220 exception
- removes ticked check for modular ss220
> Linter Fixes
